
- block:
  - name: EDIT DEVICE
    netbox.netbox.netbox_device:
      netbox_url: "{{ url_nb }}"
      netbox_token: "{{ token_nb }}"
      data:
        name: "{{ indicador.device.display }}"    
        serial: "adsad"
        custom_fields:
          cores: "{{ cpu_cores }}"
          cpu: "{{ ansible_processor[2] }}"
          cpu_cantidad: "{{ cpu_count }}"
          threads: "{{ cpu_logics }}"
          memory: "{{ ram_total }}"
          version: "{{ version }}"
          arquitectura: "{{ arquitecture }}"

      state: present
    delegate_to: localhost
    ignore_errors: yes
   
  rescue:
    - name: REPORTE DE ERROR 
      debug:
        msg: " || NO ENCONTRO ECONTRO EL EQUIPO A EDITAR || "
  

