---
- name: DEVICE FACTS
  netbox.netbox.netbox_device:
    netbox_url: "{{ url_nb }}"
    netbox_token: "{{ token_nb }}"
    data:
      name: "{{hostname}}"   
  delegate_to: localhost
  register: indicador
  ignore_errors: True
  

- name: DEBUGEAR DEVICE FACTS.
  debug:
    msg: "NO SE ENCONTRO DEVICE SE PROCEDE A CREAR "
  when: indicador is failed
    
  

- name: INCLUYENDO DEVICE PARA SU EDICION.
  include_tasks: 01_main.yml
  when: 
    - indicador is succeeded
    - indicador.device.site != "{{site_temporal}}""
  no_log: True


- name: CREATING DEVICES.
  netbox.netbox.netbox_device:
    netbox_url: "{{ url_nb }}"
    netbox_token: "{{ token_nb }}"
    data:
      name: "{{ hostname }}"
      device_type: "{{device_type}}"  # MODELO DE EQUIPO
      device_role: "{{device_role}}"
      site: "{{ site_temporal }}"
      serial: "adsad"
      platform: "{{ plataforma }}"
      custom_fields:
        cores: "{{ cpu_cores }}"
        cpu: "{{ ansible_processor[2] }}"
        cpu_cantidad: "{{ cpu_count }}"
        threads: "{{ cpu_logics }}"
        memory: "{{ ram_total }} MB"
        version: "{{ version }}"
        arquitectura: "{{ arquitecture }}"
    state: present
  delegate_to: localhost
  when: indicador is failed

