---

- name: ASSIGN TO INTERFAZ.
  include_tasks: 01_main.yml 
  vars:
    num_ip: "{{ item }}"      
    ipv4: "{{ num_ip['ipv4']['address'] }}"
    prefix: "{{num_ip['ipv4']['prefix'] }}"
   

  loop: "{{ ansible_interfaces }}"

  ignore_errors: yes
  no_log: True

