- name: Filtrando por numero de disco fisico
         #debug:
          # msg: "{{ item['number'], item['partition_style'],item['partition_count'],item['model'],item['size']|filesizeformat}}"
 
  include_tasks: 02_particiones.yml  
  
  loop: "{{ item['partitions'] }}"
  loop_control:
    loop_var: features
  no_log: True

  vars:
    disk_device: "{{item.number}}"
    size_total: "{{item['size']|filesizeformat}}"
    size_partition: "{{features['size']|filesizeformat}}"
  when: features['drive_letter'] != None
  
